cuda: True
ngpu: 1
gpu_id: '0'
model: 'VAMetric'
init_model: ''
data_dir: '/data/datasets/yt8m/Train'         # replace it with your data path
flist: './filelists/train_filelist.txt'
workers: 4
batchSize: 64
manualSeed: 
adam: True
lr: 0.001
lr_decay: 0.7
lr_decay_epoch: 10
momentum: 0.9
weight_decay: 0.0001
max_epochs: 300
print_freq: 15
epoch_save: 10
checkpoint_folder: './checkpoints'
gradient_clip: 0.01
